<?php 
require_once('con-cot/conn_sqli.php');
require_once('library.php'); 
require_once('lib/basic-functions.php'); 
require_once('lib/sqli-functions.php'); 
require_once('select-library.php');
require_once('emails_lib.php'); 
require_once('country.php');
$cal->checkValueSET();
//$cal->checkLogedIN('../login');
